### ISSUE TITLE
PHP 8, Laravel 8

### ISSUE THREAD

**Issue by necrogami** [delaford/website#43]
So this project relys on php7 and laravel 5.7 both are end of life.

What is the possibility of updating this for more modern versions? I'd be willing to assist in this.

**Comment by naknode** [comment]
@necrogami I suppose i could do Laravel Shift to move this upward. Would it be too much trouble to do it manually?

**Comment by necrogami** [comment]
Shift is more then adequate, looking over stuff it doesn't seem like shift would have any issues updating this.
